//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiestaReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiesta_Report
    {
        public int ReportId { get; set; }
        public string ReportName { get; set; }
    }
}
